recipeData:
  chartVersion: 0.0.2
  recipes:
  - version: 1.0.0
    description: anything
    components:
      spark: 3.5.0
      kafka: 3.6.0
      airflow: 2.8.0
      hbase: 2.7.0
    upgradePaths: [
      ]
