recipeData:
  chartVersion: 0.0.9
  recipes:
  - version: 2.3.1
    description: ok
    components:
      spark: 1.3.1
      kafka: 1.3.2
      airflow: 1.3.3
      hbase: 1.3.4
    upgradePaths: [
      ]
