recipeData:
  chartVersion: 3.9.6
  recipes:
  - version: 4.2.3
    description: Test
    components:
      spark: 3.8.2
      kafka: 4.2.6
      airflow: 3.4.5
      hbase: 2.2.6
    upgradePaths: [
      ]
