recipeData:
  chartVersion: 0.0.7
  releaseName: new relese 0.0.6
  catalog_name: okkkkk
  catalog_description: yummyyy
  release_date: '2026-06-03'
  catalog_status: GA
  maintainer: yesss
  recipes:
  - version: 1.0.0
    description: yesss
    release_date: '2026-06-02'
    status: GA
    release_notes: okkkk
    components:
      aditya:
        version: 2.0.0
        release_date: '2026-06-08'
        upgrade_from: []
        upgrade_to:
        - 2.0.1
    upgrade_from:
    - 0.9.0
