recipeData:
  chartVersion: 0.0.8
  recipes:
  - version: null
    description: Test1
    components:
      Kafka:
        version: 2.7.0
        upgrade_from:
        - 2.6.0
        - 2.5.0
        upgrade_to:
        - 2.8.0
        - 2.9.0
      mysql:
        version: 3.7.0
        upgrade_from:
        - 3.6.0
        upgrade_to:
        - 3.8.0
      oracle:
        version: 4.7.0
        upgrade_from:
        - 4.7.0
        upgrade_to:
        - 4.8.0
    upgradePaths: [
      ]
  - version: 1.8.0
    description: Test2
    components:
      Kafka:
        version: 2.8.0
        upgrade_from:
        - 2.7.0
        upgrade_to:
        - 2.9.0
      mysql:
        version: 3.8.0
        upgrade_from:
        - 3.7.0
        upgrade_to:
        - 3.9.0
      oracle:
        version: 4.8.0
        upgrade_from:
        - 4.7.0
        upgrade_to:
        - 4.9.0
    upgradePaths:
    - 1.7.9
