recipeData:
  chartVersion: 0.0.5
  releaseName: runtime-v0-0-5
  catalog_name: hpe ana
  catalog_description: hello
  release_date: '2026-06-09'
  catalog_status: GA
  maintainer: okkkk
  recipes:
  - version: 2.1.1
    description: hello
    release_date: '2026-06-02'
    status: Beta
    release_notes: hiiiiiiiii
    components:
      adi:
        version: 3.0.0
        release_date: '2026-06-09'
        upgrade_from:
        - 2.7.0
        upgrade_to:
        - 3.2.0
    upgrade_from:
    - 2.0.0
