recipeData:
  chartVersion: 1.1.0
  recipes:
  - version: 1.8.4
    description: test release
    components:
      spark: 1.7.2
      kafka: 1.8.2
      airflow: 1.9.2
      hbase: 2.0.0
    upgradePaths: [
      ]
